project_structure/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    # Home Page.
    path('', views.index, name='index'),
    # Search Page
    path('search/', views.search, name='search'),
    # Url for Delete.
    path('delete/<city_name>/', views.delete_city, name='delete_city'),
    # Url for clearing all cities.
    path('deleteall/', views.delete_everything, name='delete_everything'),
]

weather/models.py
from django.db import models

# Create your models here.

class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        # shows an actual string representation of the city name.
        return self.name

    class Meta:
        # Makes the plural of city, cities instead of citys.
        verbose_name_plural = 'cities'

weather/forms.py
from django.forms import ModelForm, TextInput
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'City Name'}),
        } # Updates the input class to have the correct bootstrap class and placeholder.

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""

weather/views.py
from django.shortcuts import render, redirect
import requests
from .models import City
from .forms import CityForm

from django.conf import settings
import os
from decouple import config

import json
with open('/etc/config.json') as config_file:
    config = json.load(config_file)

# Create your views here.

def index(request):
    """The home page for the weather app."""
    return render(request, 'weather/index.html')

def search(request):
    """The search page fpr the weather app."""
    url = config.get("WEATHER_URL")

    err_msg = ''
    message = ''
    message_class = ''

    if request.method == 'POST':
        form = CityForm(request.POST)
        
        # Prevents duplicate cities from being submitted.
        if form.is_valid():
            new_city = form.cleaned_data['name']
            existing_city_count = City.objects.filter(name=new_city).count()

            if existing_city_count == 0:
                r = requests.get(url.format(new_city)).json()

                if r['cod'] == 200:
                    form.save()
                else:
                    err_msg = 'City does not exist in the world.'
            else:
                err_msg = 'City already exists in the database!'
                

        if err_msg:
            message = err_msg
            message_class = 'alert alert-danger'
        else:
            message = 'City added successfully'
            message_class = 'alert alert-success'

    form = CityForm()

    cities = City.objects.all()

    weather_data = []
       
    for city in cities:

        r = requests.get(url.format(city)).json()

        city_weather = {
            'city': city.name,
            'temperature': r['main']['temp'],
            'description': r['weather'][0]['description'].title(),
            'icon': r['weather'][0]['icon']
        }
        
        weather_data.append(city_weather)

    context = {'weather_data': weather_data, 'form': form, 'message': message}

    return render(request, 'weather/search.html', context)

def delete_city(request, city_name):
    """This is used to delete individual cities."""

    City.objects.get(name=city_name).delete()

    return redirect('weather:search')

def delete_everything(request):
    """This is used to delete all the cities in the database"""

    cities = City.objects.all()
    for city in cities:
        City.objects.get(name=city).delete()

    return redirect('weather:search')

weather/templates/weather/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>IonTheSky</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body style="background-color: #58326c;">
    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">

        <a class="navbar-brand" href="{% url 'weather:index' %}">IonTheSky</a>

        <button class="navbar-toggler" type="button"      data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">

            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <button class="btn btn-sm btn-outline-secondary">
                        <a class="nav-link" href="{% url 'weather:index' %}">Home</a></li>
                    </button>
            </ul>
    </nav>

    <main role="main" class="container">
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>
</html>

weather/templates/weather/index.html
{% extends "weather/base.html" %}

{% block content %}

<div class="jumbotron">
    <h1 class="display-4">What's the weather like?</h1>
    <p class="lead">Use this Web Application to find current weather results from any city in the world!</p>
    <hr class="my-4">
    <p>Click the button below to go to the search page.</p>
    <a class="btn btn-success btn-lg" href="{% url 'weather:search' %}" role="button">search</a>
</div>

{% endblock content %}

weather/templates/weather/search.html
{% extends "weather/base.html" %}

{% block content %}

<form method='post' action="{% url 'weather:search' %}">

    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit' class='btn btn-outline-success mb-2'>Add City</button>

    {% if message %}
        <div class="{{ message_class }}" role="alert">
            {{ message }}
        </div>
    {% endif %}

</form>

<a class="btn btn-outline-danger mb-4 mt-2" href="{% url 'weather:delete_everything' %}" role="button">Remove All</a>

{% for weather in weather_data %}

    <div class="card text-center mb-4">
        
        <div class="card-header" style="background-color: #B5A6DE">
            <h2>{{ weather.city }}</h2>

            <a class="btn btn-secondary btn-sm btn-danger" href="{% url 'weather:delete_city' weather.city %}" role="button">Remove
            </a>

        </div>
        <img class="card-img mx-auto" src="http://openweathermap.org/img/w/{{ weather.icon }}.png" style="max-width: 5rem;">
        <div class="card-body">
            <h5 class="card-title">{{ weather.temperature }}° F</h5>
            <p class="card-text">{{ weather.description }}</p>
        </div>
        
    </div>

{% endfor %}

{% endblock content %}